### ISSUE TITLE
what is that?

### ISSUE THREAD

**Issue by xi2And33** [Be-UI/Be-CLI#25]

**Comment by baiwusanyu-c** [comment]
This is a cli tool for generating template projects. It has some built-in template projects, but the built-in projects are very personal. They are mainly used for companies or individuals to start new projects without rebuilding the project, but directly using this cli to produce templates. project.
这是一个生成模板项目的cli工具，内置了一些模板项目，但是内置的项目很个人化，主要用于公司或个人启动新项目时，不需要重新搭建项目，而是直接使用这个cli去生产模板项目。
